apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
spec:
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - name: web-ui
        image: web-ui
        imagePullPolicy: Never
        env:
          - name: SERVER_URI
            valueFrom:
              configMapKeyRef:
                name: product-service-configmap
                key: server-uri
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
