apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-service
spec:
  selector:
    matchLabels:
      app: basket-service
  replicas: 1
  template:
    metadata:
      labels:
        app: basket-service
    spec:
      containers:
      - name: basket-service
        image: basket-service:latest
        imagePullPolicy: Never
        env:
        - name: PORT
          value: "3001"
        ports:
        - containerPort: 3001