apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-service
spec:
  selector:
    matchLabels:
      app: basket-service
  template:
    metadata:
      labels:
        app: basket-service
    spec:
      containers:
      - name: basket-service
        image: basket-service
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3004
