apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: product-service
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3002
        env:
          - name: MONGODB_HOST
            valueFrom:
              configMapKeyRef:
                name: product-service-mongodb-configmap
                key: host
          - name: MONGODB_PORT
            valueFrom:
              configMapKeyRef:
                name: product-service-mongodb-configmap
                key: port
          - name: MONGODB_DB
            valueFrom:
              configMapKeyRef:
                name: product-service-mongodb-configmap
                key: database
          - name: MONGODB_DB_USER
            valueFrom:
              secretKeyRef:
                name: product-service-mongodb-secret
                key: mongo-root-username
          - name: MONGODB_DB_USER_PW
            valueFrom:
              secretKeyRef:
                name: product-service-mongodb-secret
                key: mongo-root-password
